### ISSUE TITLE
can i publish a npm package with this project's fork?

### ISSUE THREAD

**Issue by Rednexie** [levg34/typescript-nedb-orm#23]
https://github.com/Rednexie/nedb-odm

**Comment by levg34** [comment]
Of course! And I see the original repository is mentioned at the end of your readme, so thank you for that!

You can also contribute your changes here if you feel like it, as I see the direction you take is not opposed to what I had in mind for the future 🙂

**Comment by levg34** [comment]
And if you find a cool way to instantiate and retrieve several classes extending ORM, do not hesitate to notify me!
