### ISSUE TITLE
Only method save and find is supported currently?

### ISSUE THREAD

**Issue by atorber** [levg34/typescript-nedb-orm#5]

**Comment by levg34** [comment]
Hello @atorber ,

Yes, currently that is all, but if you have suggestions of other methods to add, feel free to list them in a reply to this issue, or contribute directly if you can/want to!

I am more than welcome to suggestions.

**Comment by atorber** [comment]
The "typescript-nedb-orm" project is quite useful, and I believe that many more people could benefit from an ORM for NeDB.

I used ChatGPT-4 to generate an ORM with more methods, but it has not been fully tested and verified yet. When I have time later on, it can be merged into your project.

```
/* eslint-disable sort-keys */
import Datastore from 'nedb'
import { EventEmitter } from 'events'

// BaseEntity class
abstract class BaseEntity {

  _id?: string
  protected static datastore: Datastore
  static events = new EventEmitter()

  static setDatastore (ds: Datastore) {
    this.datastore = ds
  }

  static on (event: string, listener: (...args: any[]) => void) {
    this.events.on(event, listener)
  }

  static async findOne<T extends typeof BaseEntity> (this: T, query: object): Promise<InstanceType<T> | null> {
    return new Promise((resolve, reject) => {
      this.datastore.findOne(query, (err, doc) => {
        if (err) reject(err)
        else resolve(doc as InstanceType<T>)
      })
    })
  }

  static async find<T extends typeof BaseEntity> (this: T, query: object): Promise<InstanceType<T>[]> {
    return new Promise((resolve, reject) => {
      this.datastore.find(query, (err: any, docs: InstanceType<T>[]) => {
        if (err) reject(err)
        else resolve(docs as InstanceType<T>[])
      })
    })
  }

  static async update<T extends typeof BaseEntity> (this: T, query: object, updateQuery: object): Promise<number> {
    return new Promise((resolve, reject) => {
      this.datastore.update(query, updateQuery, {}, (err, numReplaced) => {
        if (err) reject(err)
        else resolve(numReplaced)
      })
    })
  }

  static async remove<T extends typeof BaseEntity> (this: T, query: object): Promise<number> {
    return new Promise((resolve, reject) => {
      this.datastore.remove(query, {}, (err, numRemoved) => {
        if (err) reject(err)
        else resolve(numRemoved)
      })
    })
  }

  validate (): string[] {
    return []
  }

  async save (): Promise<void> {
    const errors = this.validate()
    if (errors.length) {
      throw new Error(errors.join(', '))
    }

    if (this._id) {
      await BaseEntity.update({ _id: this._id }, this)
      BaseEntity.events.emit('updated', this)
    } else {
      const doc = await new Promise<any>((resolve, reject) => {
        BaseEntity.datastore.insert(this, (err, newDoc) => {
          if (err) reject(err)
          else resolve(newDoc)
        })
      })

      BaseEntity.events.emit('created', this)
      this._id = doc._id
    }
  }

  async delete (): Promise<void> {
    if (this._id) {
      await BaseEntity.remove({ _id: this._id })
      BaseEntity.events.emit('deleted', this)
    } else {
      throw new Error('Entity does not have an _id and cannot be deleted.')
    }
  }

}

// User model
interface UserProps {
  _id?: string;
  name: string;
  email: string;
}

class User extends BaseEntity implements UserProps {

  name: string
  email: string

  constructor (props: UserProps) {
    super()
    this.name = props.name
    this.email = props.email
  }

  override validate (): string[] {
    const errors = []
    if (!this.name) errors.push('Name is required.')
    if (!this.email) errors.push('Email is required.')
    return errors
  }

}

// Initialization function to set up the datastore
function initDatabase (filename: string) {
  const userDB = new Datastore({ filename, autoload: true })
  User.setDatastore(userDB)
}

// Test usage
async function test () {
  initDatabase('user.db')

  const newUser = new User({ name: 'Alice', email: 'alice@example.com' })

  User.on('created', (user: User) => {
    log.info('User created:', user)
  })

  try {
    await newUser.save()
    log.info('User saved!')
  } catch (error) {
    console.error('Error saving user:', error)
  }
}

await test()

```

**Comment by levg34** [comment]
I will take a look at your pull request, and create a new issue for this.

**Comment by atorber** [comment]
如果我们能对齐Mongoose，可能会更方便开发者使用

以下是 Mongoose 的一些主要方法和功能：

1. **模型和文档创建**：
   - `mongoose.model(modelName, schema)`: 定义一个新模型。
   - `new Model(data)`: 使用给定的数据创建一个新的文档。

2. **查询**：
   - `Model.find(conditions, projection, options)`: 查找匹配条件的多个文档。
   - `Model.findOne(conditions, projection, options)`: 查找匹配条件的单个文档。
   - `Model.findById(id, projection, options)`: 通过 ID 查找单个文档。

3. **更新**：
   - `Model.update(conditions, data, options)`: 更新一个或多个文档。
   - `Model.updateOne(conditions, data, options)`: 更新单个文档。
   - `Model.findByIdAndUpdate(id, data, options)`: 通过 ID 更新单个文档。

4. **删除**：
   - `Model.remove(conditions)`: 删除匹配条件的文档。
   - `Model.deleteOne(conditions)`: 删除匹配条件的单个文档。
   - `Model.findByIdAndRemove(id)`: 通过 ID 删除单个文档。

5. **其他文档操作**：
   - `Document.save()`: 保存文档到数据库。
   - `Document.populate(path, select)`: 填充关联的文档。
   - `Document.validate()`: 验证文档。

6. **中间件**：
   - `schema.pre(hook, function)`: 在某个操作（例如 `save`、`update`）之前执行的函数。
   - `schema.post(hook, function)`: 在某个操作之后执行的函数。

7. **聚合**：
   - `Model.aggregate(pipeline)`: 对文档进行复杂的聚合操作。

8. **实用工具**：
   - `Model.count(conditions)`: 计算匹配条件的文档数量。
   - `Model.distinct(field, conditions)`: 获取某个字段的所有唯一值。
   - `Model.watch(pipeline, options)`: 监听数据库更改事件。

9. **静态方法和实例方法**：
   - 在模型的 Schema 上，你可以定义自己的静态方法或实例方法。

10. **虚拟属性**：
   - `schema.virtual(name, options)`: 定义虚拟属性，这些属性不会保存到 MongoDB，但可以在模型实例上进行设置和获取。

这只是 Mongoose 提供的一部分方法和功能的概览。为了更深入地了解 Mongoose 及其功能，建议查阅官方文档或相关教程。

**Comment by levg34** [comment]
Hi @atorber 

Thanks for your suggestions. Some have already been implemented, some with your help even.

If you could format this as a new issue with only what is missing, and in English, that would be awesome, thank you !

I am going to close this issue now.
